ktor:
  deployment:
    port: $SERVER_PORT
    sslPort: $SSL_PORT
  security:
    ssl:
      keyStore: $keyStore
      keyAlias: $keyAlias
      keyStorePassword: $keyStorePassword
      privateKeyPassword: $privateKeyPassword
  application:
    modules:
      - ru.kyamshanov.ApplicationKt.module
server:
  resources: $resources
